language: php

sudo: required

services:
    - docker

cache:
    directories:
        - "$HOME/.composer/cache"
        - "vendor"
        - "/cache/gitsplit"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
        - php: nightly
        - php: 7.2

install:
    - docker pull jderusse/gitsplit
    - git config remote.origin.fetch "+refs/*:refs/*"
    - git config remote.origin.mirror true
    - git fetch --unshallow

before_script:
    - chmod +x ./tests/install_php_ext.sh
    - if [ "$TRAVIS_PHP_VERSION" = '7.1' ]; then ./tests/install_php_ext.sh; fi
    - composer self-update
    - mkdir -p build/logs
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v ${PWD}:/srv jderusse/gitsplit
    - "./vendor/bin/phpunit --coverage-clover build/logs/clover.xml"

after_success:
    - vendor/bin/coveralls --no-interaction
